1998 dashboard should show total impact statistics
GoodDollar/GoodDashboard pull request #25
Opened 2020-06-19 14:50 UTC by yaroslav-fedyshyn-nordwhale

# Description

Added functionality to calculate and save 'totalUniqueClaimers', 'totalUBIDistributed', 'totalGDVolume' data in 'property' collection. Added addresseClaimed collection to store addresses which did claim at least once. Show 3 new total impact statistic cards at the top of the dashboard.

About https://app.zenhub.com/workspaces/gooddollar-5d50833888a83c6880d3e345/issues/gooddollar/gooddapp/1998

# How Has This Been Tested?

Go to dashboard and see 3 new total impact statistic cards.

# Checklist:
- [x] PR title matches follow: (Feature|Bug|Chore) Task Name
- [x] My code follows the style guidelines of this project
- [ ] I have followed all the instructions described in the initial task (check Definitions of Done)
- [ ] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added reference to a related issue in the repository
- [x] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [x] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [x] @mentions of the person or team responsible for reviewing proposed changes

## Screenshot:
<img width="1679" alt="1" src="https://user-images.githubusercontent.com/49862004/85145539-608c6780-b255-11ea-9909-b5ae1b1355ab.png">

2020-06-21 05:49 UTC, sirpy requested changes
code looks correct but the G$ total volume in the screenshot doesnt seem correct

2020-06-21 05:49 UTC, sirpy commented on server/src/providers/blockchain.ts
> +    const { nonExisted } = await AddressesClaimedProvider.checkIfExistsMultiple(uniqueAddresses)
the check and insert can be  done in one command using update with upsert:true and $setOnInsert
https://docs.mongodb.com/manual/reference/operator/update/setOnInsert/
and from the result read nUpserted to get the number of documents inserted

2020-06-22 06:52 UTC, yaroslav-fedyshyn-nordwhale commented
> code looks correct but the G$ total volume in the screenshot doesnt seem correct

Right, it's wrong because I did a screenshot before I fixed the calculation functionality. After fix - it becomes working correctly.

2020-06-22 08:53 UTC, serdiukov-o-nordwhale approved these changes

2020-06-23 10:52 UTC, merged